"""
Integration Tests for Resource Search and Filtering

Tests search functionality:
- Keyword search
- Category filtering
- Location filtering  
- Status filtering
- Pagination

AI Contribution: Test structure generated by Cline
Reviewed and configured by developer on 2025-11-05
"""

import pytest
from werkzeug.security import generate_password_hash

from src.models.user import User
from src.models.resource import Resource
from src.repositories.user_repo import UserRepository
from src.repositories.resource_repo import ResourceRepository


@pytest.fixture
def test_resources(app):
    """Create diverse test resources for search testing."""
    with app.app_context():
        # Create a test user
        user = User(
            name="Test Owner",
            email="owner@test.com",
            password=generate_password_hash("Owner123"),
            role="staff",
            department="Operations",
        )
        user = UserRepository.create(user)

        # Create various published resources
        resources_data = [
            {
                "title": "Study Room Alpha",
                "description": "Quiet study room with whiteboard",
                "category": "Study Space",
                "location": "Library Floor 2",
                "capacity": 6,
                "status": "published",
            },
            {
                "title": "Study Room Beta",
                "description": "Group study room with projector",
                "category": "Study Space",
                "location": "Library Floor 3",
                "capacity": 8,
                "status": "published",
            },
            {
                "title": "MacBook Pro 2023",
                "description": "Latest MacBook Pro for checkout",
                "category": "Technology",
                "location": "IT Department",
                "capacity": 1,
                "status": "published",
            },
            {
                "title": "Conference Room A",
                "description": "Large conference room for events",
                "category": "Event Space",
                "location": "Building A Room 210",
                "capacity": 50,
                "status": "published",
            },
            {
                "title": "3D Printer Lab",
                "description": "Lab with multiple 3D printers",
                "category": "Lab",
                "location": "Engineering Building",
                "capacity": 10,
                "status": "published",
            },
            {
                "title": "Draft Equipment",
                "description": "This is a draft",
                "category": "Equipment",
                "location": "Storage",
                "capacity": 1,
                "status": "draft",
            },
            {
                "title": "Archived Room",
                "description": "No longer available",
                "category": "Study Space",
                "location": "Old Building",
                "capacity": 4,
                "status": "archived",
            },
        ]

        created_resources = []
        for resource_data in resources_data:
            resource = Resource(owner_id=user.user_id, **resource_data)
            created_resources.append(ResourceRepository.create(resource))

        return created_resources


class TestKeywordSearch:
    """Test keyword search functionality."""

    def test_search_by_title(self, client, app, test_resources):
        """Test searching resources by title."""
        with app.app_context():
            # Search for "MacBook"
            response = client.get("/resources?q=MacBook")
            assert response.status_code == 200
            assert b"MacBook Pro 2023" in response.data
            assert b"Study Room" not in response.data

    def test_search_by_description(self, client, app, test_resources):
        """Test searching in resource descriptions."""
        with app.app_context():
            # Search for "projector"
            response = client.get("/resources?q=projector")
            assert response.status_code == 200
            assert b"Study Room Beta" in response.data or b"projector" in response.data

    def test_search_case_insensitive(self, client, app, test_resources):
        """Test that search is case-insensitive."""
        with app.app_context():
            # Search with lowercase
            response1 = client.get("/resources?q=macbook")
            # Search with uppercase
            response2 = client.get("/resources?q=MACBOOK")

            assert response1.status_code == 200
            assert response2.status_code == 200
            # Both should return results
            assert b"MacBook" in response1.data
            assert b"MacBook" in response2.data

    def test_search_no_results(self, client, app, test_resources):
        """Test search with no matching results."""
        with app.app_context():
            response = client.get("/resources?q=NonexistentResource123")
            assert response.status_code == 200
            # Should show empty state or no results message
            assert b"MacBook" not in response.data
            assert b"Study Room" not in response.data


class TestCategoryFilter:
    """Test filtering by category."""

    def test_filter_by_study_space(self, client, app, test_resources):
        """Test filtering for study spaces."""
        with app.app_context():
            response = client.get("/resources?category=Study Space")
            assert response.status_code == 200
            assert b"Study Room Alpha" in response.data or b"Study Room Beta" in response.data
            assert b"MacBook" not in response.data

    def test_filter_by_technology(self, client, app, test_resources):
        """Test filtering for technology resources."""
        with app.app_context():
            response = client.get("/resources?category=Technology")
            assert response.status_code == 200
            assert b"MacBook Pro 2023" in response.data
            assert b"Study Room" not in response.data

    def test_filter_by_event_space(self, client, app, test_resources):
        """Test filtering for event spaces."""
        with app.app_context():
            response = client.get("/resources?category=Event Space")
            assert response.status_code == 200
            assert b"Conference Room A" in response.data

    def test_filter_by_lab(self, client, app, test_resources):
        """Test filtering for lab resources."""
        with app.app_context():
            response = client.get("/resources?category=Lab")
            assert response.status_code == 200
            assert b"3D Printer Lab" in response.data


class TestLocationFilter:
    """Test filtering by location."""

    def test_filter_by_library(self, client, app, test_resources):
        """Test filtering for library resources."""
        with app.app_context():
            response = client.get("/resources?location=Library")
            assert response.status_code == 200
            # Should match resources in Library Floor 2 or 3
            assert b"Study Room" in response.data

    def test_filter_by_building_a(self, client, app, test_resources):
        """Test filtering for Building A resources."""
        with app.app_context():
            response = client.get("/resources?location=Building A")
            assert response.status_code == 200
            assert b"Conference Room A" in response.data


class TestCombinedFilters:
    """Test combining multiple filters."""

    def test_search_with_category_filter(self, client, app, test_resources):
        """Test combining keyword search with category filter."""
        with app.app_context():
            response = client.get("/resources?q=room&category=Study Space")
            assert response.status_code == 200
            assert b"Study Room" in response.data
            # Should not show Conference Room (different category)
            assert b"Conference Room A" not in response.data

    def test_category_with_location_filter(self, client, app, test_resources):
        """Test combining category and location filters."""
        with app.app_context():
            response = client.get("/resources?category=Study Space&location=Library")
            assert response.status_code == 200
            assert b"Study Room" in response.data


class TestStatusFiltering:
    """Test that only published resources appear in public listings."""

    def test_only_published_resources_shown(self, client, app, test_resources):
        """Test that draft and archived resources are hidden."""
        with app.app_context():
            response = client.get("/resources")
            assert response.status_code == 200

            # Published resources should be visible
            assert b"Study Room Alpha" in response.data or b"MacBook Pro 2023" in response.data

            # Draft and archived should NOT be visible
            assert b"Draft Equipment" not in response.data
            assert b"Archived Room" not in response.data

    def test_draft_not_in_search_results(self, client, app, test_resources):
        """Test that draft resources don't appear in search."""
        with app.app_context():
            response = client.get("/resources?q=Draft")
            assert response.status_code == 200
            assert b"Draft Equipment" not in response.data

    def test_archived_not_in_category_filter(self, client, app, test_resources):
        """Test that archived resources don't appear in category filters."""
        with app.app_context():
            response = client.get("/resources?category=Study Space")
            assert response.status_code == 200
            assert b"Archived Room" not in response.data


class TestPagination:
    """Test pagination functionality."""

    def test_pagination_first_page(self, client, app, test_resources):
        """Test first page of results."""
        with app.app_context():
            response = client.get("/resources?page=1")
            assert response.status_code == 200
            # Should return results (may be all if total < 20)

    def test_pagination_respects_per_page_limit(self, client, app):
        """Test that pagination limits are enforced."""
        with app.app_context():
            # Create 25 published resources
            user = User(
                name="Bulk Owner",
                email="bulk@test.com",
                password=generate_password_hash("Bulk123"),
                role="staff",
            )
            user = UserRepository.create(user)

            for i in range(25):
                resource = Resource(
                    owner_id=user.user_id,
                    title=f"Resource {i}",
                    description=f"Description {i}",
                    category="Equipment",
                    location="Storage",
                    status="published",
                )
                ResourceRepository.create(resource)

            # Get first page (default 20 per page)
            response = client.get("/resources?page=1")
            assert response.status_code == 200

            # Count how many resources are shown (should be ≤20)
            # This is a rough check - in practice would parse HTML properly
            content = response.data.decode("utf-8")
            assert "Resource" in content

    def test_empty_page_doesnt_crash(self, client, app, test_resources):
        """Test that requesting a page beyond results doesn't crash."""
        with app.app_context():
            response = client.get("/resources?page=999")
            assert response.status_code == 200


class TestSearchEdgeCases:
    """Test edge cases in search functionality."""

    def test_empty_search_returns_all(self, client, app, test_resources):
        """Test that empty search returns all published resources."""
        with app.app_context():
            response = client.get("/resources?q=")
            assert response.status_code == 200
            # Should show published resources
            assert b"Study Room" in response.data or b"MacBook" in response.data

    def test_special_characters_in_search(self, client, app, test_resources):
        """Test search with special characters."""
        with app.app_context():
            # Search with special characters that shouldn't crash
            response = client.get("/resources?q=%&*<>")
            assert response.status_code == 200

    def test_very_long_search_query(self, client, app, test_resources):
        """Test search with very long query string."""
        with app.app_context():
            long_query = "a" * 500
            response = client.get(f"/resources?q={long_query}")
            assert response.status_code == 200
