"""
Integration Tests for Resource CRUD Operations

Tests complete resource lifecycle:
- Creation (with authorization)
- Retrieval (public vs owner)
- Update (owner-only)
- Delete (owner-only, cascading file deletion)
- Status transitions (publish, archive)

AI Contribution: Test structure generated by Cline
Reviewed and configured by developer on 2025-11-05
"""

from src.models.resource import Resource
from src.repositories.user_repo import UserRepository
from src.repositories.resource_repo import ResourceRepository


def _require_user(email: str):
    user = UserRepository.get_by_email(email)
    if not user:  # pragma: no cover - safety for seeded data
        raise AssertionError(f"Seeded user {email} not found")
    return user


def _login(client, creds: dict):
    client.post(
        "/auth/login",
        data={"email": creds["email"], "password": creds["password"]},
        follow_redirects=True,
    )


class TestResourceCreation:
    """Test resource creation workflows."""

    def test_staff_can_create_resource(self, client, app, demo_seed):
        """Test that staff can create a resource and it appears in listings."""
        with app.app_context():
            _login(client, demo_seed["staff"])

            # Create resource
            resource_data = {
                "title": "Conference Room A",
                "description": "Large conference room with projector",
                "category": "space",
                "location": "Building A, Room 210",
                "capacity": 20,
                "status": "published",
            }

            create_response = client.post(
                "/resources/create", data=resource_data, follow_redirects=False
            )

            # Should redirect to detail page
            assert create_response.status_code == 302
            assert "/resources/" in create_response.location

            # Check resource appears on /resources
            list_response = client.get("/resources")
            assert list_response.status_code == 200
            assert b"Conference Room A" in list_response.data

            # Check resource appears on /my-resources
            my_resources_response = client.get("/my-resources")
            assert my_resources_response.status_code == 200
            assert b"Conference Room A" in my_resources_response.data

    def test_create_resource_as_draft(self, client, app, demo_seed):
        """Test creating a draft resource (not visible publicly)."""
        with app.app_context():
            _login(client, demo_seed["staff"])

            # Create draft resource
            resource_data = {
                "title": "Draft Resource",
                "description": "This is a draft",
                "category": "equipment",
                "location": "Storage",
                "status": "draft",
            }

            create_response = client.post(
                "/resources/create", data=resource_data, follow_redirects=True
            )

            assert create_response.status_code == 200

            # Should NOT appear on public /resources list
            list_response = client.get("/resources")
            assert b"Draft Resource" not in list_response.data

            # Should appear on /my-resources
            my_resources_response = client.get("/my-resources")
            assert b"Draft Resource" in my_resources_response.data


class TestResourceEditing:
    """Test resource edit authorization and functionality."""

    def test_owner_can_edit_resource(self, client, app, demo_seed):
        """Test that resource owner can edit their resource."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create resource as staff
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Original Title",
                description="Original description",
                category="equipment",
                location="Room 101",
                status="published",
            )
            resource = ResourceRepository.create(resource)

            # Login as staff (owner)
            _login(client, demo_seed["staff"])

            # Edit resource
            edit_data = {
                "title": "Updated Title",
                "description": "Updated description",
                "category": "equipment",
                "location": "Room 102",
                "capacity": 10,
                "status": "published",
            }

            edit_response = client.post(
                f"/resources/{resource.resource_id}/edit", data=edit_data, follow_redirects=True
            )

            assert edit_response.status_code == 200
            assert b"Updated Title" in edit_response.data

            # Verify changes in database
            updated_resource = ResourceRepository.get_by_id(resource.resource_id)
            assert updated_resource.title == "Updated Title"
            assert updated_resource.location == "Room 102"

    def test_non_owner_cannot_edit_resource(self, client, app, demo_seed):
        """Test that non-owner gets 403 when trying to edit resource."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create resource as staff
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Staff Resource",
                description="Owned by staff",
                category="equipment",
                location="Room 101",
                status="published",
            )
            resource = ResourceRepository.create(resource)

            # Login as student (not owner)
            _login(client, demo_seed["student"])

            # Attempt to edit
            edit_data = {
                "title": "Hacked Title",
                "description": "Should not work",
                "category": "equipment",
                "location": "Room 101",
            }

            edit_response = client.post(
                f"/resources/{resource.resource_id}/edit", data=edit_data, follow_redirects=True
            )

            # Should show error message
            assert (
                b"only edit your own resources" in edit_response.data
                or b"Only the resource owner" in edit_response.data
            )

            # Verify resource unchanged
            unchanged_resource = ResourceRepository.get_by_id(resource.resource_id)
            assert unchanged_resource.title == "Staff Resource"


class TestResourceDeletion:
    """Test resource deletion authorization."""

    def test_owner_can_delete_resource(self, client, app, demo_seed):
        """Test that owner can delete their resource."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create resource
            resource = Resource(
                owner_id=staff_user.user_id,
                title="To Be Deleted",
                description="This will be deleted",
                category="equipment",
                location="Room 101",
                status="published",
            )
            resource = ResourceRepository.create(resource)
            resource_id = resource.resource_id

            # Login as owner
            _login(client, demo_seed["staff"])

            # Delete resource
            delete_response = client.post(f"/resources/{resource_id}/delete", follow_redirects=True)

            assert delete_response.status_code == 200
            assert b"deleted successfully" in delete_response.data

            # Verify resource removed from database
            deleted_resource = ResourceRepository.get_by_id(resource_id)
            assert deleted_resource is None

    def test_non_owner_cannot_delete_resource(self, client, app, demo_seed):
        """Test that non-owner cannot delete resource."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create resource as staff
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Protected Resource",
                description="Should not be deletable by student",
                category="equipment",
                location="Room 101",
                status="published",
            )
            resource = ResourceRepository.create(resource)
            resource_id = resource.resource_id

            # Login as student
            _login(client, demo_seed["student"])

            # Attempt to delete
            delete_response = client.post(f"/resources/{resource_id}/delete", follow_redirects=True)

            # Should show error
            assert (
                b"Only the resource owner" in delete_response.data
                or b"only delete your own" in delete_response.data
            )

            # Verify resource still exists
            existing_resource = ResourceRepository.get_by_id(resource_id)
            assert existing_resource is not None


class TestResourceStatusTransitions:
    """Test publish and archive workflows."""

    def test_publish_draft_resource(self, client, app, demo_seed):
        """Test publishing a draft resource."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create draft resource
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Draft to Publish",
                description="Will be published",
                category="equipment",
                location="Room 101",
                status="draft",
            )
            resource = ResourceRepository.create(resource)

            # Login as owner
            _login(client, demo_seed["staff"])

            # Publish
            publish_response = client.post(
                f"/resources/{resource.resource_id}/publish", follow_redirects=True
            )

            assert publish_response.status_code == 200
            assert b"published successfully" in publish_response.data

            # Verify status changed
            published_resource = ResourceRepository.get_by_id(resource.resource_id)
            assert published_resource.status == "published"

    def test_archive_published_resource(self, client, app, demo_seed):
        """Test archiving a published resource."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create published resource
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Published to Archive",
                description="Will be archived",
                category="equipment",
                location="Room 101",
                status="published",
            )
            resource = ResourceRepository.create(resource)

            # Login as owner
            _login(client, demo_seed["staff"])

            # Archive
            archive_response = client.post(
                f"/resources/{resource.resource_id}/archive", follow_redirects=True
            )

            assert archive_response.status_code == 200
            assert b"archived" in archive_response.data

            # Verify status changed
            archived_resource = ResourceRepository.get_by_id(resource.resource_id)
            assert archived_resource.status == "archived"


class TestResourceVisibility:
    """Test resource visibility based on status."""

    def test_published_resources_visible_to_all(self, client, app, demo_seed):
        """Test that published resources appear in public listings."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create published resource
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Public Resource",
                description="Visible to everyone",
                category="study_room",
                location="Library",
                status="published",
            )
            ResourceRepository.create(resource)

            # Access without login
            list_response = client.get("/resources")
            assert list_response.status_code == 200
            assert b"Public Resource" in list_response.data

    def test_draft_resources_not_visible_publicly(self, client, app, demo_seed):
        """Test that draft resources don't appear in public listings."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create draft resource
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Secret Draft",
                description="Should not be visible",
                category="equipment",
                location="Storage",
                status="draft",
            )
            ResourceRepository.create(resource)

            # Access without login
            list_response = client.get("/resources")
            assert list_response.status_code == 200
            assert b"Secret Draft" not in list_response.data

    def test_archived_resources_not_visible_publicly(self, client, app, demo_seed):
        """Test that archived resources don't appear in public listings."""
        with app.app_context():
            staff_user = _require_user(demo_seed["staff"]["email"])
            # Create archived resource
            resource = Resource(
                owner_id=staff_user.user_id,
                title="Old Resource",
                description="Archived",
                category="equipment",
                location="Archive",
                status="archived",
            )
            ResourceRepository.create(resource)

            # Access without login
            list_response = client.get("/resources")
            assert list_response.status_code == 200
            assert b"Old Resource" not in list_response.data
